import React, { useState } from 'react'
import { Card, Btn, Alert } from '../components/UI.jsx'
import * as Icons from '../components/Icons.jsx'

export default function SupportPage() {
  const [subject, setSubject] = useState('')
  const [priority, setPriority] = useState('MEDIUM')
  const [message, setMessage] = useState('')
  const [sending, setSending] = useState(false)
  const [success, setSuccess] = useState(false)
  const [activeFaq, setActiveFaq] = useState(null)

  const faqs = [
    {
      q: 'How do I register for a Planify event?',
      a: 'Navigate to the "Events" tab from the navigation header, browse the available events, and click on the event you want to attend. From the event details page, click "Register for Event". You can view all your active tickets under the "My Tickets" tab.'
    },
    {
      q: 'How do I check-in attendees at my event?',
      a: 'If you are an Admin or an Organizer hosting an event, open the "Check-In Tool". Select your event, and you will see a list of registered attendees. You can search by attendee name or enter their unique ticket code to mark them as checked-in.'
    },
    {
      q: 'Who has permission to create and publish events?',
      a: 'Event creation is restricted to users with the "ADMIN" or "ORGANIZER" role. If your account is registered as a "PARTICIPANT" and you want to host events, please contact support to update your account role permissions.'
    },
    {
      q: 'Are tickets free or paid?',
      a: 'All tickets generated by Planify are currently managed as RSVP confirmations. There are no payment options enabled inside this application, making registrations completely free of charge.'
    }
  ]

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!subject || !message) return
    setSending(true)
    setTimeout(() => {
      setSending(false)
      setSuccess(true)
      setSubject('')
      setMessage('')
      setPriority('MEDIUM')
    }, 1200)
  }

  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      
      {/* Support Header */}
      <div style={{
        background: 'linear-gradient(135deg, var(--color-primary-light) 0%, rgba(253, 244, 255, 0.05) 100%)',
        borderRadius: 'var(--radius-lg)',
        padding: '2.5rem 2rem',
        border: '1px solid var(--color-border)',
        boxShadow: 'var(--shadow-sm)',
        position: 'relative',
        overflow: 'hidden'
      }}>
        <div style={{ position: 'relative', zIndex: 2 }}>
          <h1 style={{ fontSize: 32, fontWeight: 800, color: 'var(--color-text-heading)', marginBottom: 10, letterSpacing: '-0.03em' }}>
            Planify Support Center
          </h1>
          <p style={{ color: 'var(--color-text-muted)', fontSize: 16, fontWeight: 500, maxWidth: 640 }}>
            Have questions about our event management platform or need account assistance? We're here to support you.
          </p>
        </div>
        {/* Subtle decorative circles */}
        <div style={{
          position: 'absolute',
          top: '-20%',
          right: '-10%',
          width: 300,
          height: 300,
          borderRadius: '50%',
          background: 'radial-gradient(circle, var(--color-primary) 0%, transparent 70%)',
          opacity: 0.06,
          pointerEvents: 'none'
        }} />
      </div>

      {success && (
        <Alert type="success" onClose={() => setSuccess(false)}>
          Thank you! Your support ticket has been received. Our team will get back to you at <strong>hypeflume036@gmail.com</strong> within 24 hours.
        </Alert>
      )}

      {/* Main Grid Layout */}
      <div className="event-detail-grid">
        
        {/* Left Column: Contact Form */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <Card style={{ padding: '2rem' }}>
            <h3 style={{ fontSize: 20, fontWeight: 800, marginBottom: 6, color: 'var(--color-text-heading)' }}>
              Open a Support Ticket
            </h3>
            <p style={{ fontSize: 13, color: 'var(--color-text-muted)', marginBottom: 24, fontWeight: 500 }}>
              Send an inquiry directly to our technical customer support team.
            </p>

            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--color-neutral-700)', marginBottom: 6 }}>
                  SUPPORT EMAIL CONTACT
                </label>
                <input 
                  type="text" 
                  value="hypeflume036@gmail.com" 
                  disabled 
                  style={{ 
                    background: 'var(--color-neutral-100)', 
                    color: 'var(--color-text-muted)',
                    cursor: 'not-allowed',
                    fontWeight: 600
                  }} 
                />
              </div>

              <div className="grid-responsive-2">
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--color-neutral-700)', marginBottom: 6 }}>
                    SUBJECT <span style={{ color: 'var(--color-danger)' }}>*</span>
                  </label>
                  <input 
                    type="text" 
                    placeholder="e.g. Requesting host permissions" 
                    value={subject}
                    onChange={e => setSubject(e.target.value)}
                    required 
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--color-neutral-700)', marginBottom: 6 }}>
                    PRIORITY LEVEL
                  </label>
                  <select 
                    value={priority} 
                    onChange={e => setPriority(e.target.value)}
                    style={{ cursor: 'pointer' }}
                  >
                    <option value="LOW">Low (General Inquiry)</option>
                    <option value="MEDIUM">Medium (Default)</option>
                    <option value="HIGH">High (Urgent Help)</option>
                  </select>
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--color-neutral-700)', marginBottom: 6 }}>
                  MESSAGE CONTENT <span style={{ color: 'var(--color-danger)' }}>*</span>
                </label>
                <textarea 
                  placeholder="Describe your issue or request in detail..." 
                  value={message}
                  onChange={e => setMessage(e.target.value)}
                  rows={6}
                  required 
                />
              </div>

              <div style={{ display: 'flex', gap: 12, paddingTop: 10, borderTop: '1px solid var(--color-border)' }}>
                <Btn type="submit" variant="primary" size="lg" disabled={sending || !subject || !message}>
                  {sending ? 'Submitting Ticket...' : 'Submit Support Ticket'}
                </Btn>
              </div>
            </form>
          </Card>
        </div>

        {/* Right Column: Direct Info & FAQ */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          
          {/* Quick Contact Card */}
          <div style={{
            background: 'var(--color-bg-card)',
            border: '1px solid var(--color-border)',
            borderRadius: 'var(--radius-lg)',
            padding: '1.75rem',
            boxShadow: 'var(--shadow-sm)',
            display: 'flex',
            flexDirection: 'column',
            gap: 16
          }}>
            <h4 style={{ fontSize: 16, fontWeight: 800, color: 'var(--color-text-heading)' }}>
              Direct Support Email
            </h4>
            <p style={{ fontSize: 13, color: 'var(--color-text-muted)', lineHeight: 1.5 }}>
              For direct business inquiries, partnership requests, or security reports, email us directly:
            </p>
            
            <a 
              href="mailto:hypeflume036@gmail.com?subject=Planify Support Inquiry"
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 10,
                width: '100%',
                padding: '12px',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-primary)',
                color: '#ffffff',
                fontWeight: 700,
                fontSize: 14,
                textDecoration: 'none',
                textAlign: 'center',
                boxShadow: 'var(--shadow-sm)',
                transition: 'all 0.2s ease'
              }}
              onMouseEnter={e => e.currentTarget.style.backgroundColor = 'var(--color-primary-dark)'}
              onMouseLeave={e => e.currentTarget.style.backgroundColor = 'var(--color-primary)'}
            >
              <Icons.MailIcon size={16} />
              <span>Email Support</span>
            </a>
            
            <div style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: 8, 
              fontSize: 12, 
              color: 'var(--color-text-muted)', 
              justifyContent: 'center',
              fontWeight: 600
            }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%', backgroundColor: 'var(--color-success)' }} />
              <span>Standard Response Time: Under 24h</span>
            </div>
          </div>

          {/* Quick FAQ Card */}
          <div style={{
            background: 'var(--color-bg-card)',
            border: '1px solid var(--color-border)',
            borderRadius: 'var(--radius-lg)',
            padding: '1.75rem',
            boxShadow: 'var(--shadow-sm)'
          }}>
            <h4 style={{ fontSize: 16, fontWeight: 800, color: 'var(--color-text-heading)', marginBottom: 14 }}>
              Frequently Asked Questions
            </h4>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {faqs.map((faq, idx) => {
                const active = activeFaq === idx
                return (
                  <div 
                    key={idx}
                    style={{
                      border: '1px solid var(--color-border)',
                      borderRadius: 'var(--radius-sm)',
                      overflow: 'hidden',
                      transition: 'all 0.15s ease'
                    }}
                  >
                    <button
                      onClick={() => setActiveFaq(active ? null : idx)}
                      style={{
                        width: '100%',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        padding: '12px 14px',
                        background: active ? 'var(--color-neutral-100)' : 'transparent',
                        border: 'none',
                        textAlign: 'left',
                        cursor: 'pointer',
                        color: 'var(--color-text-heading)',
                        fontWeight: 700,
                        fontSize: 13,
                        borderRadius: 0
                      }}
                    >
                      <span>{faq.q}</span>
                      <span style={{ 
                        transform: active ? 'rotate(180deg)' : 'rotate(0deg)',
                        transition: 'transform 0.15s ease',
                        fontSize: 10,
                        color: 'var(--color-neutral-400)'
                      }}>
                        ▼
                      </span>
                    </button>
                    {active && (
                      <div style={{ 
                        padding: '12px 14px', 
                        fontSize: 13, 
                        color: 'var(--color-text-muted)', 
                        lineHeight: 1.5,
                        backgroundColor: 'var(--color-bg-card)',
                        borderTop: '1px solid var(--color-border)'
                      }}>
                        {faq.a}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </div>

        </div>

      </div>

    </div>
  )
}
